window:
  dimensions:
    columns: 213
    lines: 47
  position:
    x: 2560
    y: 0
  padding:
    x: 2
    y: 2
  opacity: 1.0

font:
  size: 14.0
  normal:
    family: UDEV Gothic NF
    style: Regular
  bold:
    family: UDEV Gothic NF
    style: Bold
  italic:
    family: UDEV Gothic NF
    style: Italic

cursor:
  style:
    blinking: on

scrolling:
  history: 10000

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }
  - { key: Q,      mods: Control|Shift, action: ToggleViMode }
  - { key: Plus,  mods: Control|Shift, action: IncreaseFontSize }

import:
  - "~/.config/alacritty/solarized.yml"
